### ISSUE TITLE
建议(依赖、图形/功能参考)

### ISSUE THREAD

**Issue by sky5454** [poemdistance/ScreenTranslation#1]
1. Linux 依赖方面可以使用 git 的依赖 submodule 或者 subtree ，这样就不用手动拉依赖代码了  
2. python 模块的依赖可以用一键生成列表并安装，参考： https://www.cnblogs.com/LearningOnline/articles/9778495.html
3. 图形或功能可以参考浏览器插件 [沙拉查词 saladict](https://github.com/crimx/ext-saladict)

**Comment by poemdistance** [comment]
好的老哥，我去看一下。
刚又更新了一下，要试的话，Python翻译和这边项目两边最好都更新一下，我这测试一般都是同步着的，有问题还麻烦告知 :D
