### ISSUE TITLE
窗口顶栏 可以弄消失吗;还有显示的位置

### ISSUE THREAD

**Issue by junknet** [poemdistance/ScreenTranslation#15]
这些还是比较影响阅读原文的...
title 应该有个 title.hide() 之类的吧..
窗口显示在鼠标指针右下角:python版本的.
        (x, y) = Gtk.Window.get_position()
        (w, h) = Gtk.Window.get_size()
        Gtk.Window.move(x + w / 2, y + h / 2)
        Gtk.Window.show_all()

**Comment by poemdistance** [comment]
@junknet 
![image](https://user-images.githubusercontent.com/28592567/75619403-4e0ef500-5bb6-11ea-88ca-a2c9d95925df.png)

隐藏红色指针那里的标题栏吗？
没有大问题的话下次更新可以加上。

**Comment by poemdistance** [comment]
已经放了一个临时更新，去掉了标题栏，窗口位置我再研究一下，容易加进去的话，稍后放上更新，最近在写自定义快捷键等一些大更新，加上了前面一个issue提到的图标消失时间调整功能，还没融合，有什么功能各位可以提一下，有必要的可以统一加进去。

![image](https://user-images.githubusercontent.com/28592567/75620443-068f6580-5bc4-11ea-85a6-5c1a1b8664c8.png)
