### ISSUE TITLE
在安装的prepare过程，sed: can't read Mstran.desktop: No such file or directory

### ISSUE THREAD

**Issue by loonggi** [poemdistance/ScreenTranslation#16]
sed: can't read Mstran.desktop: No such file or directory
cp: cannot stat 'Mstran.desktop': No such file or directory

Note: Please check whether the device 'mice' is belong to 'input'
because it might be wrong result

/dev/input/mice is belong to the group of "input"
Adding current user to group "input"

注意: 加入的组在重启后生效，在此之前需要使用sudo执行程序

另外一个问题就是，看这个log，意思是我在make prepare的时候需要加sudo么？

**Comment by poemdistance** [comment]
@Hongki-Long 看报错，怀疑是不是没到src/目录下执行命令？Mstran.desktop是src下的一个文件，其实是软件的桌面入口图标，用来启动软件的。内容如下：
```
[Desktop Entry]
Name=Mstran                    
Comment=The Monitor of ScreenTranslation
Exec=/home/rease/.stran/startup.sh
Icon=/home/rease/.stran/tran.png
Type=Application               
Terminal=false
Categories=GTK;GNOME;
```
可以手动修改rease为自己的用户名。跟sed指令是一样的效果。
`make prepare` 不需要sudo, 脚本内部已经加上了sudo,安装过程会提示输入用户密码

**Comment by poemdistance** [comment]
@Hongki-Long 我好像想起来了点什么
```
Exec=/home/rease/.stran/startup.sh
Icon=/home/rease/.stran/tran.png
```
其中的rease原本应该是$USER,不小心被覆盖成了我自己的用户名，所以解决办法是手动修改成自己的用户名就可以了，再继续执行安装命令。
