### ISSUE TITLE
在make prepare出现loading 'build.ninja': No such file or directory和cannot stat 'src/gnome-screenshot': No such file or directory的错误

### ISSUE THREAD

**Issue by loonggi** [poemdistance/ScreenTranslation#17]
在执行make prepare以下命令时，出现了loading 'build.ninja': No such file or directory和cannot stat 'src/gnome-screenshot': No such file or directory的错误

————————————————prepare.sh—————————————————
system=`uname -a`
if [[ $system =~ .*"deepin".* ]]; then
    sudo apt install gnome-screenshot
else
    cd ../gnome-screenshot
    sudo bash install.sh
fi
—————————————————error——————————————————
Directory does not contain a valid build tree:
/home/longkj/ScreenTranslation/gnome-screenshot/builddir
ninja: error: loading 'build.ninja': No such file or directory
Install data not found. Run this command in build directory root.
cp: cannot stat 'src/gnome-screenshot': No such file or directory

另外，我的builddir文件夹为空。

**Comment by poemdistance** [comment]
@Hongki-Long 
可以不用安装这个（是个截图软件，目前暂时被禁用），不影响使用。
或者可手动安装：
Debian系列：`sudo apt install gnome-screenshot`
Arch：`pacman -S gnome-screenshot`
其他发行版请自寻。
安装脚本出错的问题有时间再解决。

**Comment by poemdistance** [comment]
已移除子模块：gnome-screenshot
改由自动识别发行版并命令行安装此软件
问题不再存在
