### ISSUE TITLE
运行mstran时出错

### ISSUE THREAD

**Issue by JincanDeng** [poemdistance/ScreenTranslation#2]
` ( Monitor ) Parent process, child pid =10886
shared memeory already exist,reference shmid = 1051918343
Attach to 0x7ffc38ef6458 

shared memeory already exist,reference shmid = 1051951126
Attach to 0x7ffc38ef6460 

执行谷歌翻译程序 
Execv error (google)
Failed to open mice                    
Try to execute as superuser or add                     current user to group which /dev/input/mice belong to
执行百度翻译程序 
Execv error (baidu)
stran 子进程已退出, 准备重新启动... 
(Monitor) Parent process in while, new child process id 10891 
shared memeory already exist,reference shmid = 1051918343
Attach to 0x7ffdb9084638 

shared memeory already exist,reference shmid = 1051951126
Attach to 0x7ffdb9084640 

执行谷歌翻译程序 
Execv error (google)
Failed to open mice                    
Try to execute as superuser or add                     current user to group which /dev/input/mice belong to
执行百度翻译程序 
Execv error (baidu)
stran 子进程已退出, 准备重新启动... 
(Monitor) Parent process in while, new child process id 10896 
shared memeory already exist,reference shmid = 1051918343
Attach to 0x7ffe841e8d68 

shared memeory already exist,reference shmid = 1051951126
Attach to 0x7ffe841e8d70 

执行谷歌翻译程序 
Execv error (google)
Failed to open mice                    
Try to execute as superuser or add                     current user to group which /dev/input/mice belong to
执行百度翻译程序 
Execv error (baidu)
stran 子进程已退出, 准备重新启动... 
(Monitor) Parent process in while, new child process id 10901 
shared memeory already exist,reference shmid = 1051918343
Attach to 0x7ffc72f109f8 

shared memeory already exist,reference shmid = 1051951126
Attach to 0x7ffc72f10a00 

执行谷歌翻译程序 
Execv error (google)
Failed to open mice                    
Try to execute as superuser or add                     current user to group which /dev/input/mice belong to
执行百度翻译程序 
Execv error (baidu)
stran 子进程已退出, 准备重新启动... 
失败尝试次数过多, 请检测网络是否正常再重新运行监控程序 
bash: /home/can/.stran/notification.sh: 没有那个文件或目录`

安装过程没有出现问题,执行 mstran 时出现以上错误.
系统为 ubuntu18 ,桌面环境为 gnome.

**Comment by poemdistance** [comment]
原因是当前用户不在/dev/input/mice所在组，所以无法打开这个鼠标设备文件，如果执行了`bash prepare.sh`脚本应该是已经加入其所在组了的，估计是没重启，重启之后就可以了。

另外也可以用`sudo mstran`执行。

加入组的命令如下(在bash里有这个类似语句，如果加入失败，尝试如下命令)：
usermod -aG \`ls -l /dev/input/mice | awk '{print $4}' | xargs\` $USER

成功与否用命令 `groups $USER` 查看，输出结果有一个为
echo \`ls -l /dev/input/mice | awk '{print $4}' | xargs\`的输出结果

**Comment by JincanDeng** [comment]
@poemdistance 嗯嗯,现在可以用了.感觉用起来很不错.
非常感谢!!!

**Comment by poemdistance** [comment]
@JincanDeng 嗯嗯，有问题随时提issue，也可以帮我推荐一下，人多了，完善的机会才会越来越多，有兴趣的可以pull一下request，感觉Linux一直缺个好用的取词翻译软件，如果能有一个逐步完善发展起来对于广大程序员查看各种英文相关技术文章来说会方便很多。

另外，readme添加了更新此软件的方式，欢迎查阅~

**Comment by JincanDeng** [comment]
@JincanDeng 哈哈，这么好用的软件，一定推广给大家～
