### ISSUE TITLE
致命错误：can't create obj/configControl.o: 没有那个文件或目录

### ISSUE THREAD

**Issue by GenmCai** [poemdistance/ScreenTranslation#21]
➤ make                                                                  17:14:50
make -C CommonSrc
make[1]: 进入目录“/home/genmcai/GitFile/ScreenTranslation/src/CommonSrc”
编译.o文件
gcc -c -fno-stack-protector -Wall -lm -lX11 -lXtst -lXext -lpthread -lXfixes -ggdb -g -Wno-deprecated-declarations `pkg-config --cflags --libs gtk+-3.0 gstreamer-1.0 libbsd libbsd-ctor` -Iinclude -I../CommonHeader/ -fPIC src/configControl.c -o obj/configControl.o
Assembler messages:
致命错误：can't create obj/configControl.o: 没有那个文件或目录
make[1]: *** [Makefile:28：obj/configControl.o] 错误 1
make[1]: 离开目录“/home/genmcai/GitFile/ScreenTranslation/src/CommonSrc”
make: *** [Makefile:5：all] 错误 2

**Comment by poemdistance** [comment]
没开Linux系统，暂时测试不了，从错误上看是obj目录忘了自动创建。
解决办法：
在“/home/genmcai/GitFile/ScreenTranslation/src/CommonSrc”目录下，创建obj文件夹。
相关命令: `mkdir obj`

**Comment by GenmCai** [comment]
gcc -Iinclude -I../CommonHeader/  obj/configControl.o  obj/expanduser.o  obj/shmCreate.o  obj/strmask.o  obj/useful.o -shared -o ../lib/libshared.so
/usr/bin/ld: cannot open output file ../lib/libshared.so: 没有那个文件或目录
collect2: 错误：ld 返回 1
make[1]: *** [Makefile:24：../lib/libshared.so] 错误 1
make[1]: 离开目录“/home/genmcai/GitFile/ScreenTranslation/src/CommonSrc”
make: *** [Makefile:5：all] 错误 2

大大，这个libshared.so该如何解决。。。

**Comment by poemdistance** [comment]
试一下在 /home/genmcai/GitFile/ScreenTranslation/src/ 下创建  lib 文件夹

**Comment by GenmCai** [comment]
make[2]: 离开目录“/home/genmcai/GitFile/ScreenTranslation/src/Settings/src”
make -C test
make[2]: 进入目录“/home/genmcai/GitFile/ScreenTranslation/src/Settings”
make[2]: *** test: 没有那个文件或目录。 停止。
make[2]: 离开目录“/home/genmcai/GitFile/ScreenTranslation/src/Settings”
make[1]: *** [Makefile:5：all] 错误 2
make[1]: 离开目录“/home/genmcai/GitFile/ScreenTranslation/src/Settings”
make: *** [Makefile:7：all] 错误 2

大大新错误。。。

**Comment by poemdistance** [comment]
@GenmCai 
原因： test目录被gitignore忽略，没有提交到github平台
目前已经提交成功，git pull跟上游同步后重新make就行。

**Comment by GenmCai** [comment]
感谢大大，问题解决了。软件非常不错，不过很多都没有语音，如果常用的单词都有语音，那就更优秀了。

**Comment by poemdistance** [comment]
@GenmCai 
可以看一下readme关于离线库的安装，包含48万多个离线单词，大部分都有语音。
另外谷歌翻译本身没有语音，偶尔能看到有语音其实是来自离线翻译或者必应翻译。
我记得有个bug还没动手解决，在谷歌翻译界面显示了语音播放按钮，如果其源来自必应，那么点击后将没有反应。
最后你说的很多没有语音能不能贴上一些实例，我测试一下。

**Comment by GenmCai** [comment]
现在试了以后发现都是可以的，之前测试的对象是这个项目的README Icon position，之前测试的时候是没有可用语音的，还有其它找不到语音的单词，是我随手翻译了下打开的文档发现的，具体已经忘记是那个了，不过现在测试却是可以，可能的原因是网络的问题，软件环境是还没有装离线库。而目前尝试出不能语音的单词是 readme，其它测试过的都是有语音的，而使用了几十分钟的感觉是，除了划词翻译的响应速度有点小慢，其它都挺不错。

还有关于设计的建议:
1. 划词翻译后，软件图标离单词较远，可以的话，希望能近一点（可能是受有道翻译的影响，感觉有道翻译的距离比较合适）。
2. 在查看翻译区时，不希望双击播放语音，就把翻译区放大，翻译区放大的事件倒是可以放在翻译区的空白区域。
3. 翻译区离划词翻译的相对位置也是有点远，可以的话，还是希望缩进下距离。

目前的体验是如此，个人感觉真的是很不错的，来linux也是为了学习，如果不注意的话，根本不会有啥跟windows上的翻译体验有啥不同。

**Comment by poemdistance** [comment]
响应速度是对动作识别准确性的妥协，相关内容展开比较多不细讲，这个确实是没办法。

readme不是一个单词，当然没有语音（手动狗头）。

对于建议1，可以打开软件的设置窗口进行调整（设置入口：Shift+Ctrl+M 或 状态栏图那里点击进入 或 点击翻译界面的设置图标 ）
对于建议2，呃，这个没看懂
对于建议3，也是可以在设置窗口进行调整。

**Comment by GenmCai** [comment]
readme的话有道倒是有语音，可能并不是传统的单词。

建议2的话，大大可以试试双击播放语音，会发现窗口会全屏，我个人是觉得这种效果不符合使用的场景。但可能每个人体验不一样，也许其他人不会有违和感。

还有就是很抱歉之前没有看全项目的README，提出了没营养的建议。

而对于程序居然包含了建议1和建议3的功能，真的让人惊叹。

**Comment by poemdistance** [comment]
@GenmCai 
嗯嗯，建议2可以采纳，有时间我加个可选功能，由用户自己决定双击含义，比如双击也可以切换翻译源。
readme内容颇多，没看全可以理解，不必在意，反正issue不多，处理得过来。

**Comment by GenmCai** [comment]
大大，一个语句的翻译是有什么技术难点吗，我看有道的翻译也没实现这个功能

**Comment by poemdistance** [comment]
可以作为一个领域来研究了：https://www.zhihu.com/question/59282269

**Comment by poemdistance** [comment]
问题解决, 关闭issue
