### ISSUE TITLE
是哪一步出错了？

### ISSUE THREAD

**Issue by chssx** [poemdistance/ScreenTranslation#22]
atal: 不是一个 git 仓库（或者直至挂载点 / 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
fatal: 不是一个 git 仓库（或者直至挂载点 / 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
Requirement already satisfied: mysql-connector-python in /usr/lib/python3.8/site-packages (8.0.20)
Requirement already satisfied: protobuf>=3.0.0 in /usr/lib/python3.8/site-packages (from mysql-connector-python) (3.12.2)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.8/site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (from protobuf>=3.0.0->mysql-connector-python) (41.2.0)
Could not build wheels for mysql-connector-python, since package 'wheel' is not installed.
Could not build wheels for protobuf, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for setuptools, since package 'wheel' is not installed.
cp: 无法获取'Mstran.desktop' 的文件状态(stat): 没有那个文件或目录

Preparing to install submodules

ERROR: Could not open requirements file: [Errno 2] 没有那个文件或目录: 'requirements.txt'
sudo: ./setup.py：找不到命令
chmod: 无法访问 '/usr/bin/bdtran': 没有那个文件或目录
cat: files.txt: 没有那个文件或目录
chmod: “775” 后缺少操作数
请尝试执行 "chmod --help" 来获取更多信息。
ERROR: Could not open requirements file: [Errno 2] 没有那个文件或目录: 'requirements.txt'
sudo: ./setup.py：找不到命令
Requirement already satisfied: mysql-connector-python in /usr/lib/python3.8/site-packages (8.0.20)
Requirement already satisfied: protobuf>=3.0.0 in /usr/lib/python3.8/site-packages (from mysql-connector-python) (3.12.2)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.8/site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (from protobuf>=3.0.0->mysql-connector-python) (41.2.0)
Could not build wheels for mysql-connector-python, since package 'wheel' is not installed.
Could not build wheels for protobuf, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for setuptools, since package 'wheel' is not installed.
cat: files.txt: 没有那个文件或目录
chmod: “775” 后缺少操作数
请尝试执行 "chmod --help" 来获取更多信息。
ERROR: Could not open requirements file: [Errno 2] 没有那个文件或目录: 'requirements.txt'
sudo: ./setup.py：找不到命令
cat: files.txt: 没有那个文件或目录
chmod: “775” 后缺少操作数
请尝试执行 "chmod --help" 来获取更多信息。
警告：gnome-screenshot-3.36.0-1 已经为最新 -- 重新安装
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) gnome-screenshot-3.36.0-1

全部安装大小：  0.87 MiB
净更新大小：  0.00 MiB

:: 进行安装吗？ [Y/n] 
(1/1) 正在检查密钥环里的密钥                                [################################] 100%
(1/1) 正在检查软件包完整性                                  [################################] 100%
(1/1) 正在加载软件包文件                                    [################################] 100%
(1/1) 正在检查文件冲突                                      [################################] 100%
(1/1) 正在检查可用存储空间                                  [################################] 100%
:: 正在处理软件包的变化...
(1/1) 正在重新安装 gnome-screenshot                         [################################] 100%
:: 正在运行事务后钩子函数...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Compiling GSettings XML schema files...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
make -C CommonSrc
make[1]: 进入目录“/home/chssx/Program/ScreenTranslation-master/src/CommonSrc”
编译.o文件
gcc -c -fno-stack-protector -Wall -lm -lX11 -lXtst -lXext -lpthread -lXfixes -ggdb -g -Wno-deprecated-declarations `pkg-config --cflags --libs gtk+-3.0 gstreamer-1.0 libbsd libbsd-ctor` -Iinclude -I../CommonHeader/ -fPIC src/configControl.c -o obj/configControl.o
/bin/sh: pkg-config：未找到命令
src/configControl.c:2:10: 致命错误：gdk/gdk.h：没有那个文件或目录
    2 | #include <gdk/gdk.h>
      |          ^~~~~~~~~~~
编译中断。
make[1]: *** [Makefile:30：obj/configControl.o] 错误 1
make[1]: 离开目录“/home/chssx/Program/ScreenTranslation-master/src/CommonSrc”
make: *** [Makefile:5：all] 错误 2

**Comment by poemdistance** [comment]
@chssx 刚推了个更新，你更新后重试下。
另外，你需要先安装`pkg-config`这个软件；
其次，要保证子模块里面内容不为空。

**Comment by chssx** [comment]
> @
好的，我试试看，谢谢！

**Comment by chssx** [comment]
[chssx@long ScreenTranslation]$ mysql -h127.0.0.1 -u$USER -p dict < dict.sql
Enter password: 
ERROR 1044 (42000): Access denied for user ''@'localhost' to database 'dict'

最后一步好难。。

**Comment by poemdistance** [comment]
@chssx 
如果按照readme里一步步设置了的话,这里密码是空,直接回车就行.
如果不是,则你前面可能有些步骤设置错了,给的信息不够,看不出问题在哪.

**Comment by poemdistance** [comment]
@chssx 
不一定非要按照readme里的进行设置.
主要是创建好数据库然后导入数据就行,另外要保证python那边能够连接上数据库.
![image](https://user-images.githubusercontent.com/28592567/85780830-9cdd2d80-b757-11ea-81c3-d486cda6631f.png)
比如,如果自己设置了其他用户名和密码,在上面所示代码里填写相应内容就好

**Comment by chssx** [comment]
> @chssx
> 不一定非要按照readme里的进行设置.
> 主要是创建好数据库然后导入数据就行,另外要保证python那边能够连接上数据库.
> ![image](https://user-images.githubusercontent.com/28592567/85780830-9cdd2d80-b757-11ea-81c3-d486cda6631f.png)
> 比如,如果自己设置了其他用户名和密码,在上面所示代码里填写相应内容就好

弄好了，非常感谢。

**Comment by chssx** [comment]
我发现个问题，Alt+D不能划词。
单词也发音不了。

**Comment by poemdistance** [comment]
> 我发现个问题，Alt+D不能划词。
> 单词也发音不了。

呃呃,能不能详细一点.
Alt+D是截图翻译, 是不能划词的, 另外单词发音不了是指?

**Comment by chssx** [comment]
截图翻译，不弹出翻译框。
单词发音就是翻译框里面那个小喇叭，按了没声音。

**Comment by poemdistance** [comment]
> 截图翻译，不弹出翻译框。
> 单词发音就是翻译框里面那个小喇叭，按了没声音。

其实截图翻译比较鸡肋, 有些没提取出字符就自然不会弹出来, 全部都不弹出来应该有些环节出了问题, 你这信息太少很难判断.
点击按钮不发音我知道的有一种情况, 但是你这描述读不出任何有价值的东西.
我还是希望遇到问题提个对应的issue, 有截图最好贴上截图, 说明是翻译哪个单词出了问题, 产生了什么不该有的现象, 抑或全部单词都出现了一样的问题, 其次贴上log, 位置在/var/log/mstran.log

**Comment by poemdistance** [comment]
安装问题已解决, 关闭issue

**Comment by poemdistance** [comment]
安装问题已解决, 关闭issue
