### ISSUE TITLE
按照步骤来的 最后make报错

### ISSUE THREAD

**Issue by diaodeyi** [poemdistance/ScreenTranslation#24]
obj/newNormalWin.o: In function `adjustTargetPosition':
/home/rjs/Downloads/ScreenTranslation/src/Main/src/newNormalWin.c:99: undefined reference to `gdk_display_get_monitor_at_window'
/home/rjs/Downloads/ScreenTranslation/src/Main/src/newNormalWin.c:99: undefined reference to `gdk_monitor_get_workarea'
collect2: error: ld returned 1 exit status
Makefile:24: recipe for target 'bin/stran' failed
make[1]: *** [bin/stran] Error 1
make[1]: Leaving directory '/home/rjs/Downloads/ScreenTranslation/src/Main'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by diaodeyi** [comment]
然后打开软件闪退

**Comment by poemdistance** [comment]
@diaodeyi 
依赖装好了没有, gdk_monitor_get_workarea 这个函数没找到, 是依赖库的函数
