### ISSUE TITLE
JNA support

### ISSUE THREAD

**Issue by kqvanity** [poemdistance/ScreenTranslation#29]
Hello,
I've been working on this java project that relies on system events such as yours text highlight cords, mouse click on, click away, etc. The problem is I'm not familiar with C++ nor X11, so I was wondering if you could port/append these two/three events to [this JNA](https://github.com/matthiasblaesing/JNA-Demos/blob/master/XFixesSelection/src/main/java/eu/doppel_helix/dev/xfixesselection/Main.java) example. Thanks

**Comment by poemdistance** [comment]
文本高亮是桌面自带的功能，鼠标点击的相关事件在这个项目里是直接读取了鼠标设备进行判断的，实现上跟x11没什么关系，不建议这么操作。另外我不写java，很遗憾帮不了你

**Comment by kqvanity** [comment]
Okay NP. Thank  you!
