### ISSUE TITLE
强烈建议使用 xclip 直接提取选中的字符

### ISSUE THREAD

**Issue by jiangzc** [poemdistance/ScreenTranslation#3]
现在的做法是是模拟 Ctrl + C 按键，然后获取剪贴板内容，这种做法不好。各种BUG 处理起来费时费力，还干扰了剪贴板内容！  建议使用 xclip命令 直接提取选中的字符

**xclip命令可以直接提取选中的字符**
> http://terminalmage.net/2011/10/18/clipboard-access-from-the-command-line.html

xsel and xclip are two commands that allow you to interact with the X clipboards. Before I explain how to use them though, a short overview of the X clipboards is in order.

X11 has not one, not two, but three clipboards. They are called:

+ PRIMARY - Also known as the "primary selection" or the "primary clipboard". This clipboard is populated whenever you highlight text with the mouse. If you've ever highlighted text and noticed that you can paste it by clicking the middle button on your mouse, this is the clipboard being used.  
+ SECONDARY - This clipboard is very rarely used anymore, but exists to provide a "secondary selection" clipboard to accompany the primary selection.
+ CLIPBOARD - This is the clipboard you are likely most familiar with. It is the one used when you copy text from an application such as a web browser, or a GUI text editor like gedit.

简单来说 X11有三个剪贴板，PRIMARY 剪贴板是鼠标选中的内容 ，CLIPBOARD 是GUI复制粘贴的内容。看一下 man xclip 你就会了

**Comment by poemdistance** [comment]
我理解的没错的话，xclip是需要一个输入的，无论是从文件中读取内容还是从stdin中，内容都已存在，之后等待某个selection的owner请求获取内容，xclip接收请求后将获取到的内容反馈回去，下次粘贴文本时发送获取某个selection内容的请求，将上一次写入的结果取出进行粘贴。

看了源码也是这么一个逻辑，这是X服务设计造成的。

所以xclip并不具备直接从屏幕提取字符的功能，如果没有模拟复制到剪贴板这么一个动作，字符便没办法提取出来，模拟Ctrl-C只是一个中介，目标是能够将字符从屏幕转移到剪贴板，以便获取。

至于污染剪贴板，这个应该可能有办法解决，后面我试一下。

**Comment by jiangzc** [comment]
鼠标选中一段内容，这个内容自动输入到了 primary剪贴板中。
你这样试试：
1. 鼠标选中一段内容
2. 终端执行  `xclip -o `

**Comment by poemdistance** [comment]
还真是，那有时获取不及时的问题应该可以解决了。哈哈，前面白看了，都不知道还可以这样。

**Comment by poemdistance** [comment]
哦，我理解的没错，xclip确实不能帮我们提取出屏幕上的字符，但是我一直以来没发现，每次选中字符的时候，X服务已经将对应的文本写入到了剪贴板，只不过不是在第一条（第一条字符串后面，第二条），调用xclip -o的时候，它也只是获取到已经存在在剪贴板的第二条内容。

如果你系统有剪贴板管理工具，也可以试一下，随便点一下字符串，看是不是对应文本出现在了第二条那里。搜狗输入法输入Ctrl + ; 可以调出

哇，我错过了什么...

**Comment by poemdistance** [comment]
老哥非常感谢，由此issue发现了惊天大秘密般激动啊！！！，不用模拟复制了，直接从Primary selection中获取的数据就是屏幕选中的，代码都不用重新设计了，直接改一个单词就行！！！

**Comment by poemdistance** [comment]
爬了快20万的单词了，继续努力到时再弄个离线功能美滋滋 :D

**Comment by poemdistance** [comment]
@jiangzc 问一个问题，有没有办法判断当前鼠标是在选中文字而非拖动窗口或者缩放窗口？
因为鼠标按住左键移动，进行选文和拖动窗口对于键值来说都是一样的，从而导致误判。当然也可以从其他方面入手讨论解决这个问题。

**Comment by jiangzc** [comment]
我的思路是这样的：选中文字前后primary selection中的内容会发生变化，其他操作例如拖动窗口前后 primary selection 内容不变。
可以参考这个项目 https://github.com/ziqiangxu/words-picker/tree/master/words-picker
不知道是什么原理，似乎没有判断鼠标

**Comment by jiangzc** [comment]
words-picker 这个项目用的是QT中的 QClipboard 控件，没有监听鼠标事件，但是有QClipboard::selectionChanged 事件

https://github.com/ziqiangxu/words-picker/blob/ffaca96818722d55eaddc21539479ad41a988bfe/words-picker/picker.cpp#L5-L14

**Comment by poemdistance** [comment]
这个发布时已经完成了，目前代码的解决方案还是如此，但有副作用：

1. 不能连续复制翻译相同的内容

2. 偶有错误弹出

**Comment by poemdistance** [comment]
@jiangzc 找到一个Xlib的拓展，可以检测Selectioin的变化并发出事件通知。[X11 Wait for and Get Clipboard Text](https://stackoverflow.com/questions/8755471/x11-wait-for-and-get-clipboard-text)

不过缺点就是复制操作和拼音输入都会触发这个事件，导致复制文本或者拼音输入后进行窗口拖拽引发误判，弹出入口图标。

另一个缺点是事件通知没有鼠标检测快，且有间断（出现在划词过程，稍有停顿，事件通知便会改变，虽然鼠标还没有释放可以继续取词），不另开进程基本无法正确判断鼠标取词事件，如果抛弃鼠标检测，只监听剪贴板，就会无法准确判断出取词结束事件（事件有间断的原因），猜测之前你发的那个作者的项目因为这个原因需要在取词过程中一直显示着入口图标，当然也可能不是。

以上问题都一一解决了，已移进项目并发布，本地测试基本没有再发生误弹出问题。

**Comment by jiangzc** [comment]
我试了一下，效果很好。有个问题 窗口默认的宽度有的小，内容显示不全，需要左右拖动。建议稍微调大一点  系统环境 deepin 15.11
![image](https://user-images.githubusercontent.com/13901512/64482374-5566ce80-d223-11e9-9917-96b5f5ad880d.png)

![image](https://user-images.githubusercontent.com/13901512/64482383-729b9d00-d223-11e9-9984-d77b7788a691.png)

**Comment by jiangzc** [comment]
英文解释中经常出现一个问题 ，一个单词被割裂为两行（上一行末尾  下一行开头），阅读起来不方便
![image](https://user-images.githubusercontent.com/13901512/64482446-ad520500-d224-11e9-965f-8e0e69a4730b.png)

**Comment by poemdistance** [comment]
@jiangzc 哈哈哈，这些本地测试时都遇到过，因为懒，没去弄 :D

我之后稍加处理一下，可能需要调试一段时间。

**Comment by poemdistance** [comment]
![image](https://user-images.githubusercontent.com/28592567/64483376-79caa700-d233-11e9-8f3c-5fbed4e67428.png)
图标偏移有点奇怪，我这里不会，窗口太小我这里也不会，因为窗口大小我是计算了横向字符长度自动调整的，高度是根据行数自动调整，音频图标都是在音标后面。

初步推测是翻译速度没跟上，在结果没获取时就算出的行数和横向字符都是0或很低，导致计算出的宽高小于最后应该需要的。

有几个问题需要了解清楚，是每个单词的翻译结果，音频播放按钮都偏移了，还是偶尔几个？

还有需要描述一下出问题时候的具体操作过程，或者可以在出问题时把`/var/log/mstran.log`贴上来，需要看一下此时的内部执行流程好定位问题。重启软件会自动清空log，所以如果重启了可能需要再重点一下那几个出问题的单词在贴上来。

单词被分割的就不用了。

**Comment by jiangzc** [comment]
每个单词的翻译结果，音频播放按钮都偏移了
查询了 package  something disk 这三个单词，发现音频播放按钮 相对于窗口的位置是固定的，向下滚动变成下面这样

![image](https://user-images.githubusercontent.com/13901512/64483658-f6ac4f80-d238-11e9-84c4-4ad6fffd3919.png)

日志
[mstran.log](https://github.com/poemdistance/ScreenTranslation/files/3587305/mstran.log)

**Comment by poemdistance** [comment]
装了个同版本号的Deeping，奇怪的是我这边窗口大小是合适的，查看了一下你贴的日志，宽度跟我在各平台测试时也都一样，我在Arch， Ubuntu， Kaili，Deeping测试都显示正常，因为界面逻辑是窗口大小必须正好容纳所有文本，所以就没让音频播放按钮自动滚动调整。

现在主要是要找出你那边为什么显示有问题，这边不好复现不太好调，代码逻辑在我这边测试看上去都没问题。

至于音频按钮有偏移这个我想个办法优化代码逻辑，看能否获取窗口信息自动适应一下，不采用固定坐标。

![show](https://user-images.githubusercontent.com/28592567/64484796-e355b000-d249-11e9-88d6-7d58df1b8824.png)

能否录个屏我看一下。

**Comment by jiangzc** [comment]
我知道了  缩放问题。之前我系统开启了1.25倍的缩放，设置成1 正常
@poemdistance

**Comment by poemdistance** [comment]
这个就很迷了，我这边随便缩放显示都正常，无论是Arch，Deeping，Ubuntu都一样。还真没想到这个问题。

猜测Gtk内部应该有自适应缩放功能，这点问题那些强大的开发者应该早就想过。至于你那边为什么这样就真不知道了。

刚开了个issue，相关界面排版的问题那边讨论，方便后来人。
