### ISSUE TITLE
xdotool 也能监测鼠标， 不需要读取 /dev/input/mice 

### ISSUE THREAD

**Issue by jiangzc** [poemdistance/ScreenTranslation#4]
xdotool 能监测鼠标，还可以避免 Issue #2  `当前用户不在/dev/input/mice所在组，所以无法打开这个鼠标设备文件` 的问题。

**Comment by poemdistance** [comment]
OK, 有时间可以重构这部分的代码实现，其实知道Xlib也是可以的，代码是当初是操作设备文件玩的时候留下来的，直接移进了项目。
