### ISSUE TITLE
窗口大小未能容纳翻译结果文本内容，音频播放按钮位置偏移

### ISSUE THREAD

**Issue by poemdistance** [poemdistance/ScreenTranslation#5]

**Comment by poemdistance** [comment]
看一下这个：[可能是系统缩放设置问题](https://github.com/poemdistance/ScreenTranslation/issues/3#issuecomment-529177824)

音频播放按钮在不同平台可能偏移不一样，尚未解决，准备着手解决。

**Comment by jiangzc** [comment]
窗口大小未能容纳翻译结果文本内容的解决方案

解决方案:1： 设置GDK 3 环境变量 (GDK_SCALE 似乎只能接受整数，效果不好)
```bash
export GDK_SCALE=2
export GDK_DPI_SCALE=0.8
mstran
```

> https://wiki.archlinux.org/index.php/HiDPI_(简体中文)#非整数倍缩放

解决方案2：修改源码重新编译
newWindow.c  1179行  width 再乘 1.2 
separateData.c   265行  gw.width 再乘 1.2 

https://github.com/poemdistance/ScreenTranslation/blob/48aa7c87bae8f68179b7e0908424546722c7eb34/src/newWindow.c#L1177-L1180

https://github.com/poemdistance/ScreenTranslation/blob/48aa7c87bae8f68179b7e0908424546722c7eb34/src/separateData.c#L264-L267

保存后 make && make install

**Comment by poemdistance** [comment]
音频按钮偏移已解决，原因是Deeping里本软件GUI单行占用长度与Arch，Ubuntu等不同，一个是17像素，一个是18像素，固定位置的设置导致最后的相对位置发生变化。

GTK在文本显示界面没有实现（realize）的时候无法准确获取字符位置（不被认为是bug的bug）[详情点击这里](https://bugzilla.gnome.org/show_bug.cgi?id=130075)

但还能根据这不准确的值获取到单行占用的像素点，只有17和18这两个数据，便用一次函数拟合了一下（if，else判断也能解决），所以其他情况可能不一定拟合的很好，可根据后面遇到其他不同情况再选用拟合，因为无法获取到准确位置，所以目前只想到用拟合的方式。

音频按钮的x坐标与音标占用长度的关系用3次函数拟合，本地测试效果还不错，也可以用if eles分支来模拟分段函数，效果应该会更好。

**Comment by poemdistance** [comment]
音频播放按钮位置偏移调整：

1. 打开src/audioPlayer.c

2. 找到 gtk_layout_put ( (GtkLayout*)layout, button, posx,  40 );  <有两条语句>

3. 适当修改值40，如果音频按钮往上偏，改大此值，反之改小。

后期再想其他解决办法，目前暂未找到。

**Comment by jiangzc** [comment]
更新到最新版后  播放按钮不显示，按照楼上的方法修改后才显示。
运行程序后，有时会出现黑框
![深度截图_选择区域_20190915185343](https://user-images.githubusercontent.com/13901512/64920424-31d6f180-d7ea-11e9-8454-59d6d9a68e68.png)

环境  deepin 15.11  
日志
[mstran.log](https://github.com/poemdistance/ScreenTranslation/files/3613661/mstran.log)

**Comment by poemdistance** [comment]
网上查了一下，貌似是Gtk的bug，渲染有点问题，重绘窗口后又会恢复。

我在Deeping上测试的时候以为是分配的资源不足导致的，就没有深究，原来你那里也会，Ubuntu也是放在虚拟机里测试，但是跟Arch一样，都很ok。

新更新的代码在背景同步里加入了重绘整个窗口的两行代码，可能能够将黑屏刷新掉。

还有你的日志是上一个版本的，目前已经把启动脚本startup.sh更新了，换成日志追加方式，如果是命令行直接运行程序，日志是不会写入mstran.log的，用图标启动或者startup.sh启动才会。

另如果程序异常退出，相关资源和进程没有被清理干净，可以运行 sh stop.sh 清掉，不然会影响到后面程序的正常运行。

**Comment by poemdistance** [comment]
重新设计了UI，文本和窗口大小以及各按钮位置可以由GTK自动调整，问题解决
