### ISSUE TITLE
图片转文字功能的想法

### ISSUE THREAD

**Issue by jiangzc** [poemdistance/ScreenTranslation#7]
百度AI 通用文字识别可以实现图片转文字的功能，准确度非常高。
我准备用python写这个功能   

百度AI参考：
https://ai.baidu.com/tech/ocr/general   
https://ai.baidu.com/docs#/OCR-API/top

**Comment by poemdistance** [comment]
可以一试，功能实现后看如何跟这个项目融合，到时再商议下C和Python端数据传输的相关协议。

需要考虑截图的问题，是自己写还是调用别人的，无论用哪种方式，快捷键调出用起来会比较顺手。

我还有一个想法，添加一个Quick Search功能，可以在任何地方用快捷键调出下面这个界面

![image](https://user-images.githubusercontent.com/28592567/64540704-2c455b80-d353-11e9-8ca9-1b1d10cb78e9.png)

获取输入后进行翻译，因为有时候是想查中文对应的英文，不是翻译屏幕上的。

还有最近可能需要闭关一段时间，不能及时回复，见谅。

**Comment by jiangzc** [comment]
截图可以用gnome-screenshot  `gnome-screenshot --area -f /tmp/ocr.png`
快捷键可能要 x11 xlib 监听键盘
OCR功能我正在做
